In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [5]:
print(a.shape)

(3,)


In [8]:
np.zeros(2)

array([0., 0.])

In [9]:
np.ones(4)            # array of ones
np.arange(0,10,2)     # 0 to 8, step 2
np.linspace(0,1,5)    # 5 equally spaced numbers between 0–1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)      # element-wise addition
print(a * b)      # element-wise multiplication
print(a.mean())   # average
print(a.max())    # max value


[11 22 33]
[10 40 90]
2.0
3


In [12]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr[0, 1])   # element (row 0, col 1) = 2
print(arr[:, 1])   # all rows, 2nd column
print(arr[1:3, :2])# subarray rows 1–2, cols 0–1


2
[2 5 8]
[[4 5]
 [7 8]]


In [13]:
a.sum()

np.int64(6)

In [14]:
arr.sum()                   # total sum
arr.sum(axis=0)             # column-wise sum
arr.sum(axis=1)             # row-wise sum


array([ 6, 15, 24])